name: mmoInfoBed
version: ${releaseVersion}.${buildNumber}
description: Adds a {bed} token to the mmoInfo token list.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Info.MMOInfoBed
depend: [Spout, mmoCore, mmoInfo]

permissions:
    mmo.info.bed:
        description: Allows {bed} to show the player's respawn coords
        default: op
